# Nexys Video Pin Assignments
############################
# On-board Slide Switches  #
############################


set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sysclk]
create_clock -period 10.000 -name sysclk -waveform {0.000 5.000} [get_ports sysclk]

# Pmod header JA
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[0]}]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[1]}]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[2]}]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[3]}]
set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[4]}]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[5]}]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[6]}]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[7]}]
# Pmod header JB
set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[8]}]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[9]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[10]}]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[11]}]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[12]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[13]}]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[14]}]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_c[15]}]

# Pmod header JC
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[0]}]
set_property -dict {PACKAGE_PIN AA6 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[1]}]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[2]}]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[3]}]
set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[4]}]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[5]}]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[6]}]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[7]}]


# XADC Header
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[8]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[9]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[10]}]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[11]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[12]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[13]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[14]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {m_axis_data_tdata_b[15]}]


connect_debug_port u_ila_0/clk [get_nets [list sysclk_IBUF_BUFG]]
connect_debug_port dbg_hub/clk [get_nets sysclk_IBUF_BUFG]

set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[11]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[7]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[12]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[8]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[10]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[14]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[8]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[15]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[7]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[13]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[12]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[10]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[9]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[11]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[14]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_c_OBUF[15]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[13]}]
set_property MARK_DEBUG true [get_nets {m_axis_data_tdata_b_OBUF[9]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sysclk_IBUF]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {m_axis_data_tdata_c_OBUF[0]} {m_axis_data_tdata_c_OBUF[1]} {m_axis_data_tdata_c_OBUF[2]} {m_axis_data_tdata_c_OBUF[3]} {m_axis_data_tdata_c_OBUF[4]} {m_axis_data_tdata_c_OBUF[5]} {m_axis_data_tdata_c_OBUF[6]} {m_axis_data_tdata_c_OBUF[7]} {m_axis_data_tdata_c_OBUF[8]} {m_axis_data_tdata_c_OBUF[9]} {m_axis_data_tdata_c_OBUF[10]} {m_axis_data_tdata_c_OBUF[11]} {m_axis_data_tdata_c_OBUF[12]} {m_axis_data_tdata_c_OBUF[13]} {m_axis_data_tdata_c_OBUF[14]} {m_axis_data_tdata_c_OBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {m_axis_data_tdata_b_OBUF[0]} {m_axis_data_tdata_b_OBUF[1]} {m_axis_data_tdata_b_OBUF[2]} {m_axis_data_tdata_b_OBUF[3]} {m_axis_data_tdata_b_OBUF[4]} {m_axis_data_tdata_b_OBUF[5]} {m_axis_data_tdata_b_OBUF[6]} {m_axis_data_tdata_b_OBUF[7]} {m_axis_data_tdata_b_OBUF[8]} {m_axis_data_tdata_b_OBUF[9]} {m_axis_data_tdata_b_OBUF[10]} {m_axis_data_tdata_b_OBUF[11]} {m_axis_data_tdata_b_OBUF[12]} {m_axis_data_tdata_b_OBUF[13]} {m_axis_data_tdata_b_OBUF[14]} {m_axis_data_tdata_b_OBUF[15]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sysclk_IBUF]
