# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Study/FPGA/FrequencyModulator/FrequencyModulator.cache/wt [current_project]
set_property parent.project_path D:/Study/FPGA/FrequencyModulator/FrequencyModulator.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/sources_1/coe/sin.coe
add_files -quiet d:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.dcp
set_property used_in_implementation false [get_files d:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.dcp]
add_files -quiet d:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/sources_1/ip/c_addsub_0/c_addsub_0.dcp
set_property used_in_implementation false [get_files d:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/sources_1/ip/c_addsub_0/c_addsub_0.dcp]
add_files -quiet d:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/sources_1/ip/mult_gen_0/mult_gen_0.dcp
set_property used_in_implementation false [get_files d:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/sources_1/ip/mult_gen_0/mult_gen_0.dcp]
read_verilog -library xil_defaultlib D:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/sources_1/new/FrequencyModulator.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/constrs_1/new/FM_xdc.xdc
set_property used_in_implementation false [get_files D:/Study/FPGA/FrequencyModulator/FrequencyModulator.srcs/constrs_1/new/FM_xdc.xdc]


synth_design -top FrequencyModulator -part xc7a200tsbg484-1


write_checkpoint -force -noxdef FrequencyModulator.dcp

catch { report_utilization -file FrequencyModulator_utilization_synth.rpt -pb FrequencyModulator_utilization_synth.pb }
